bug: 43275 Check exit status of the ldap start command, and reset things if starting ldap fails
http://bugzilla.zimbra.com/show_bug.cgi?id=43275

diff --git a/ZimbraServer/src/libexec/zmldapenablereplica b/ZimbraServer/src/libexec/zmldapenablereplica
--- a/ZimbraServer/src/libexec/zmldapenablereplica
+++ b/ZimbraServer/src/libexec/zmldapenablereplica
@@ -229,6 +229,12 @@ resetLdapUrl() {
 startLdap() {
 	echo -n "Starting LDAP on ${zimbra_server_hostname}..."
 	${zimbra_home}/bin/ldap start > /dev/null 2>&1
+	if [ $? == 1 ]; then
+  		echo "Error: Unable to start ldap, exiting."
+		resetLdapUrl
+		zmsetvars -f ldap_url
+		exit 1;
+	fi
 	echo "done"
 }
 stopLdap() {
