bug: 82177 Allow .gz, .bz2 files to be imported
http://bugzilla.zimbra.com/show_bug.cgi?id=82177

diff --git a/ZimbraServer/src/libexec/zmslapadd b/ZimbraServer/src/libexec/zmslapadd
--- a/ZimbraServer/src/libexec/zmslapadd
+++ b/ZimbraServer/src/libexec/zmslapadd
@@ -33,6 +33,19 @@ if [ $u != ${zimbra_user} ]; then
     exit 1
 fi
 
+zgood=no
+bgood=no
+zcat=`which zcat 2>/dev/null`
+bzcat=`which bzcat 2>/dev/null`
+
+if [ -x $zcat ]; then
+	zgood=yes
+fi
+
+if [ -x $bzcat ]; then
+	bgood=yes
+fi
+
 if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
 	echo "USAGE: Imports LDAP databases"
 	echo "Main database: zmslapadd <FILE>"
@@ -41,7 +54,6 @@ if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
 	exit 1
 fi
 
-D=`date +%Y%m%d%H%M%S`
 CONFIG=no
 ALOG=no
 if [ x$1 = "x-c" ]; then
@@ -54,15 +66,48 @@ else
 	SRC=$1
 fi
 
+comp=0
+computil=
+if [[ "$SRC" == *".gz" ]]; then
+	if [ x$zgood = "xno" ]; then
+		echo "Error: zcat is missing.\n"
+		exit 1
+	fi
+	computil=$zcat
+	comp=1
+elif [[ "$SRC" == *".bz2" ]]; then
+	if [ x$bgood = "xno" ]; then
+		echo "Error: bzcat is missing.\n"
+		exit 1
+	fi
+	computil=$bzcat
+	comp=1
+fi
+
 if [ x$CONFIG = "xyes" ]; then
-	${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -n 0 -l $SRC
-	RETVAL=$?
+	if [ x$comp = "x0" ]; then
+		${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -n 0 -l $SRC
+		RETVAL=$?
+	else
+		$computil $SRC | ${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -n 0
+		RETVAL=$?
+	fi
 elif [ x$ALOG = "xyes" ]; then
-	${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -b "cn=accesslog" -l $SRC
-	RETVAL=$?
+	if [ x$comp = "x0" ]; then
+		${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -b "cn=accesslog" -l $SRC
+		RETVAL=$?
+	else
+		$computil $SRC | ${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -b "cn=accesslog"
+		RETVAL=$?
+	fi
 else
-	${zimbra_home}/openldap/sbin/slapadd -w -q -F ${zimbra_home}/data/ldap/config -b "" -l $SRC
-	RETVAL=$?
+	if [ x$comp = "x0" ]; then
+		${zimbra_home}/openldap/sbin/slapadd -w -q -F ${zimbra_home}/data/ldap/config -b "" -l $SRC
+		RETVAL=$?
+	else
+		$computil $SRC | ${zimbra_home}/openldap/sbin/slapadd -w -q -F ${zimbra_home}/data/ldap/config -b ""
+		RETVAL=$?
+	fi
 fi
 
 exit $RETVAL
