http://bugzilla.zimbra.com/show_bug.cgi?id=14069 bug: 14069
Added /opt/zimbra/libexec/zmbackupldap script that handles ldap backup on a node that has ldap service running.  This script is not to be executed directly from shell.

Changed /opt/zimbra/bin/zmbackup script to invoke zmbackupldap if the host doesn't have mailbox service enabled.  If mailbox service is present, zmbackup simply sends BackupRequest SOAP command to the mailbox server, but doesn't invoke zmbackupldap.

The backup handler in mailbox server will optionally invoke zmbackupldap over ssh connection, if the node also has ldap service enabled.  This happens during both full and incremental backups.  This way, backups started from Admin Console will include ldap dump.

diff --git a/ZimbraServer/src/libexec/zmslapcat b/ZimbraServer/src/libexec/zmslapcat
--- a/ZimbraServer/src/libexec/zmslapcat
+++ b/ZimbraServer/src/libexec/zmslapcat
@@ -16,7 +16,7 @@
 # The Original Code is: Zimbra Collaboration Suite Server.
 # 
 # The Initial Developer of the Original Code is Zimbra, Inc.
-# Portions created by Zimbra are Copyright (C) 2005, 2006 Zimbra, Inc.
+# Portions created by Zimbra are Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
 # All Rights Reserved.
 # 
 # Contributor(s):
@@ -24,14 +24,15 @@
 # ***** END LICENSE BLOCK *****
 # 
 
-if [ x`whoami` != xzimbra ]; then
-	echo Error: must be run as zimbra user
-	exit 1
-fi
-
 source /opt/zimbra/bin/zmshutil || exit 1
 zmsetvars \
 	zimbra_home 
+
+u=`id -un`
+if [ $u != ${zimbra_user} ]; then
+    echo "Error: must be run as ${zimbra_user} user"
+    exit 1
+fi
 
 if [ ! -L ${zimbra_home}/openldap ]; then
 	# No ldap - exit gracefully
