bug: none IO lib must be compiled on RHEL4, RHEL4_64, and MAC.

diff --git a/ThirdParty/Perl/Makefile b/ThirdParty/Perl/Makefile
--- a/ThirdParty/Perl/Makefile
+++ b/ThirdParty/Perl/Makefile
@@ -39,6 +39,14 @@ ifeq ($(BUILD_PLATFORM), MACOSX)
 endif
 ifeq ($(BUILD_PLATFORM), MACOSXx86)
 	MYSQL_INCLUDE := $(ZIMBRA_HOME)/mysql/include/mysql
+	IO_LIB := IO
+endif
+
+ifeq ($(BUILD_PLATFORM), RHEL4)
+	IO_LIB := IO
+endif
+ifeq ($(BUILD_PLATFORM), RHEL4_64)
+	IO_LIB := IO
 endif
 
 # DESTINATIONS
@@ -171,6 +179,12 @@ all: setup $(DEST_LIB_DIR) $(PERL_TGZ_DEST_DIR)
 		if [ $$? -ne 0 ]; then  echo "FAILED.";  else  echo "done.";  fi \
 	done
 	
+	@for lib in $(IO_LIB); do \
+		echo -n "Compiling perl lib $$lib ..."; \
+		LDFLAGS="-fPIC" CFLAGS="-fPIC" BERKELEYDB_INCLUDE=$(BDB_INC) BERKELEYDB_LIB=$(BDB_LIB) $(PERL) -I$(DEST_LIB_DIR) -MCPAN -e "$$CPAN::Config->{make_arg}.=' CCCDLFLAGS="-fPIC" CFLAGS="-fPIC" LDFLAGS="-fPIC"'; $$CPAN::Config->{makepl_arg}.=' CCCDLFLAGS="-fPIC" CFLAGS="-fPIC" LDFLAGS="-fPIC"'; force (\"install\", \"$$lib\")" >> $(LOGFILE) 2>&1; \
+		if [ $$? -ne 0 ]; then  echo "FAILED.";  else  echo "done.";  fi \
+	done
+
 	@for lib in $(PERL_LIBS); do \
 		echo -n "Compiling perl lib $$lib ..."; \
 		LDFLAGS="-fPIC" CFLAGS="-fPIC" BERKELEYDB_INCLUDE=$(BDB_INC) BERKELEYDB_LIB=$(BDB_LIB) $(PERL) -I$(DEST_LIB_DIR) -MCPAN -e "$$CPAN::Config->{make_arg}.=' CCCDLFLAGS="-fPIC" CFLAGS="-fPIC" LDFLAGS="-fPIC"'; $$CPAN::Config->{makepl_arg}.=' CCCDLFLAGS="-fPIC" CFLAGS="-fPIC" LDFLAGS="-fPIC"'; force (\"install\", \"$$lib\")" >> $(LOGFILE) 2>&1; \
