Integrated the following from //depot/zimbra/HELIX/...: Change 322776 by bpeterson@brian-helix on 2011/07/26 08:18:24
bug:  61963
check exit status of zmcpolicydinit.

http://bugzilla.zimbra.com/show_bug.cgi?id=61963

diff --git a/ZimbraCBPolicyd/src/bin/zmcbpolicydctl b/ZimbraCBPolicyd/src/bin/zmcbpolicydctl
--- a/ZimbraCBPolicyd/src/bin/zmcbpolicydctl
+++ b/ZimbraCBPolicyd/src/bin/zmcbpolicydctl
@@ -78,6 +78,10 @@ case "$1" in
       fi
       if [ ! -f ${dbfile} ]; then
         ${zimbra_home}/libexec/zmcbpolicydinit
+        if [ $? != 0 ]; then
+          echo "Unable to initialize cbpolicyd database." 
+          exit 1
+        fi
       fi
       if [ x$2 = "x" ]; then
         rewriteconfig
