bug: 76960 Don't allow MTA commands to execute on non-mta nodes
http://bugzilla.zimbra.com/show_bug.cgi?id=76960

diff --git a/ZimbraServer/src/bin/postconf b/ZimbraServer/src/bin/postconf
--- a/ZimbraServer/src/bin/postconf
+++ b/ZimbraServer/src/bin/postconf
@@ -22,4 +22,9 @@ zmsetvars \
 	zimbra_home \
 	zimbra_server_hostname 
 
+if [ ! -L /opt/zimbra/postfix ]; then
+  echo "Error: postfix not installed"
+  exit 1
+fi
+
 sudo ${zimbra_home}/postfix/sbin/postconf "$@"
diff --git a/ZimbraServer/src/bin/postfix b/ZimbraServer/src/bin/postfix
--- a/ZimbraServer/src/bin/postfix
+++ b/ZimbraServer/src/bin/postfix
@@ -17,6 +17,12 @@
 progdir=`dirname $0`
 
 source `dirname $0`/zmshutil || exit 1
+
+if [ ! -L /opt/zimbra/postfix ]; then
+  echo "Error: postfix not installed"
+  exit 1
+fi
+
 zmsetvars \
 	zimbra_home \
   postfix_mail_owner \
diff --git a/ZimbraServer/src/bin/zmmtactl b/ZimbraServer/src/bin/zmmtactl
--- a/ZimbraServer/src/bin/zmmtactl
+++ b/ZimbraServer/src/bin/zmmtactl
@@ -22,6 +22,11 @@ zmsetvars \
 
 BASE=${zimbra_home:=/opt/zimbra}
 
+if [ ! -L /opt/zimbra/postfix ]; then
+  echo "Error: postfix not installed"
+  exit 1
+fi
+
 if [ -f "${zimbra_home}/conf/mta_milter_options" ]; then
   source ${zimbra_home}/conf/mta_milter_options
 fi
