bug: 62182 If AV isn't installed, don't try and start up
http://bugzilla.zimbra.com/show_bug.cgi?id=62182

diff --git a/ZimbraServer/src/bin/zmamavisdctl b/ZimbraServer/src/bin/zmamavisdctl
--- a/ZimbraServer/src/bin/zmamavisdctl
+++ b/ZimbraServer/src/bin/zmamavisdctl
@@ -19,6 +19,11 @@ if [ x`whoami` != xzimbra ]; then
   exit 1
 fi
 
+if [ ! -L "/opt/zimbra/amavisd" ]; then
+  echo "Error: Amavis is not installed"
+  exit 1
+fi
+
 export LD_LIBRARY_PATH=/opt/zimbra/openldap/lib:/opt/zimbra/openssl/lib:$LD_LIBRARY_PATH
 
 source `dirname $0`/zmshutil || exit 1
diff --git a/ZimbraServer/src/bin/zmantivirusctl b/ZimbraServer/src/bin/zmantivirusctl
--- a/ZimbraServer/src/bin/zmantivirusctl
+++ b/ZimbraServer/src/bin/zmantivirusctl
@@ -17,6 +17,11 @@
 BASE=/opt/zimbra
 SCRIPTS="zmamavisdctl zmclamdctl zmfreshclamctl"
 
+if [ ! -L "/opt/zimbra/amavisd" ]; then
+  echo "Error: Antivirus not installed"
+  exit 1
+fi
+
 source /opt/zimbra/.bashrc
 
 case "$1" in 
diff --git a/ZimbraServer/src/bin/zmclamdctl b/ZimbraServer/src/bin/zmclamdctl
--- a/ZimbraServer/src/bin/zmclamdctl
+++ b/ZimbraServer/src/bin/zmclamdctl
@@ -19,6 +19,11 @@ if [ x`whoami` != xzimbra ]; then
   exit 1
 fi
 
+if [ ! -L "/opt/zimbra/clamav" ]; then
+  echo "Error: ClamAV not installed"
+  exit 1
+fi
+
 platform=`/opt/zimbra/libexec/get_plat_tag.sh`
 
 source `dirname $0`/zmshutil || exit 1
