Integrated the following from //depot/zimbra/IRONMAIDEN/...: Change 414725 by ayee@ayee-dev3-IRONMAIDEN on 2012/11/01 20:59:16
Bug: 78002
Prevent zmantispamdbpasswd from running (attempt to change password) if MySQL is not enabled for antispam.

http://bugzilla.zimbra.com/show_bug.cgi?id=78002

diff --git a/ZimbraServer/src/bin/zmantispamdbpasswd b/ZimbraServer/src/bin/zmantispamdbpasswd
--- a/ZimbraServer/src/bin/zmantispamdbpasswd
+++ b/ZimbraServer/src/bin/zmantispamdbpasswd
@@ -19,7 +19,14 @@
 # MySQL.
 #
 source `dirname $0`/zmshutil || exit 1
-zmsetvars zimbra_home antispam_mysql_user antispam_mysql_root_password
+zmsetvars zimbra_home antispam_mysql_user antispam_mysql_root_password antispam_mysql_enabled
+
+antispam_mysql_enabled=`echo ${antispam_mysql_enabled} | tr [:upper:] [:lower:]`
+if [ "${antispam_mysql_enabled}x" != "truex" ]
+then
+    echo "Spamassassin is not set up to use MySQL backend database!  Aborting..."
+    exit 1
+fi
 
 #
 # Usage.
