bug: 10692    startup script consistency    - add result messages for zmconvertdctl start/stop/reload/restart/status    - add result messages for zmapachectl start/stop/reload/restart/status    - add result messages for zmclamdctl status
http://bugzilla.zimbra.com/show_bug.cgi?id=10692

diff --git a/ZimbraServer/src/bin/zmapachectl b/ZimbraServer/src/bin/zmapachectl
--- a/ZimbraServer/src/bin/zmapachectl
+++ b/ZimbraServer/src/bin/zmapachectl
@@ -22,27 +22,49 @@ PIDFILE=$BASE/log/httpd.pid
 case "$1" in
 	start)
 		if [ -f $APACHECTL ]; then
+      echo -n "Starting apache..."
 			$APACHECTL -k $1 -f $CONF
-			exit $?
+      status=$?
+      if [ $status = 0 ]; then
+        echo "done."
+      else
+        echo "failed."
+      fi
+			exit $status
 		fi
 		exit 0
 	;;
   reload|graceful)
 		if [ -f $APACHECTL ]; then
+      echo -n "Reloading apache..."
 			$APACHECTL -k graceful -f $CONF
-			exit $?
+      status=$?
+      if [ $status = 0 ]; then
+        echo "done."
+      else
+        echo "failed."
+      fi
+			exit $status
 		fi
 		exit 0
 	;;
   restart)
     $0 stop
+    sleep 1
     $0 start
   ;;
 	stop)
 		if [ -f $PIDFILE ]; then
 			if [ -f $APACHECTL ]; then
+        echo -n "Stopping apache..."
 				$APACHECTL -k $1 -f $CONF
-				exit $?
+        status=$?
+        if [ $status = 0 ]; then
+          echo "done."
+        else
+          echo "failed."
+        fi
+			  exit $status
 			fi
 		fi
 		exit 0
@@ -51,19 +73,19 @@ case "$1" in
     if [ -f $PIDFILE ]; then
 		  pid=$(cat $PIDFILE)
       if [ x"$pid" = "x" ]; then
-        echo "Apache not running."
+        echo "apache is not running."
         exit 1
       fi
     else
-      echo "Apache not running.  No PID file found."
+      echo "apache is not running."
       exit 1
     fi
 		kill -0 $pid
     if [ $? = 0 ]; then
-      echo "Apache running with PID $pid"
+      echo "apache is running."
       exit 0
     else 
-      echo "Apache not running."
+      echo "apache is not running."
 		  exit 1
     fi
 	;;
