bug: 22964    use ca_file when verifying commercial certs
http://bugzilla.zimbra.com/show_bug.cgi?id=22964

diff --git a/ZimbraServer/src/bin/zmcertmgr b/ZimbraServer/src/bin/zmcertmgr
--- a/ZimbraServer/src/bin/zmcertmgr
+++ b/ZimbraServer/src/bin/zmcertmgr
@@ -559,7 +559,7 @@ createServerCert() {
   #why do we need verify the crt here? The cert is not even created yet.
   #We need to allow validation_days to be changed
   if [ -s "${server_crt}" -a "x${IS_NEW_CRT}" != "x-new" ]; then
-	$0 verifycrt self ${server_key} ${server_crt} > /dev/null 2>&1
+  $0 verifycrt self ${server_key} ${server_crt} > /dev/null 2>&1
     if [ $? = 0 ]; then
       echo "** ${server_crt} already exists."
       return
@@ -585,8 +585,8 @@ createServerCert() {
     cp -f /dev/null ${zimbra_ca_directory}/index.txt
     chmod 644 ${zimbra_ca_directory}/index.txt
   fi
-	
-  #echo "validation days = " + 	${validation_days} 
+  
+  #echo "validation days = " +   ${validation_days} 
   openssl ca -out ${server_crt} -notext \
     -config ${zimbra_ca_ssl_conf} \
     -days ${validation_days} \
@@ -864,18 +864,18 @@ deploycrt() {
       fi
 
       if [ x"$cli_comm_crt" != "x" ]; then
-	      #$0 verifycrt comm ${commercial_key} ${cli_comm_crt} > /dev/null 2>&1
-	      $0 verifycrt comm ${commercial_key} ${cli_comm_crt}
+        #$0 verifycrt comm ${commercial_key} ${cli_comm_crt} > /dev/null 2>&1
+        $0 verifycrt comm ${commercial_key} ${cli_comm_crt} ${cli_ca_chain}
         if [ $? != 0 ]; then
-          echo "${ERROR_PREFIX} provided cert doesn't match private key."
+          echo "${ERROR_PREFIX} provided cert isn't valid."
           exit 1
         fi
         echo "** Copying ${cli_comm_crt} to ${commercial_crt}"
         cp -f ${cli_comm_crt} ${commercial_crt}
       else
-	      $0 verifycrt comm ${commercial_key} ${crt_download_file}
+        $0 verifycrt comm ${commercial_key} ${crt_download_file} ${ca_chain_download_file}
         if [ $? != 0 ]; then
-          echo "${ERROR_PREFIX} provided cert doesn't match private key."
+          echo "${ERROR_PREFIX} provided cert isn't valid."
           exit 1
         fi
         echo "** Copying ${crt_download_file} to ${commercial_crt}"
@@ -921,21 +921,30 @@ verifycrt() {
     type=$1 
     shift
     key=$1
-  	crt=$2
+    crt=$2
+    ca_crt=$3
     if [ x"${key}" = "x" ] ; then
-    	if [ "$type" = "self" ]; then
-      		key=${server_key}
-    	elif [ "$type" = "comm" ]; then
-      		key=${commercial_key}
-      	fi
+      if [ "$type" = "self" ]; then
+          key=${server_key}
+      elif [ "$type" = "comm" ]; then
+          key=${commercial_key}
+        fi
     fi
   
- 	if [ x"${crt}" = "x" ] ; then
-    	if [ "$type" = "self" ]; then
-      		crt=${server_crt}
-    	elif [ "$type" = "comm" ]; then
-      		crt=${commercial_crt}
-      	fi
+   if [ x"${crt}" = "x" ] ; then
+      if [ "$type" = "self" ]; then
+          crt=${server_crt}
+      elif [ "$type" = "comm" ]; then
+          crt=${commercial_crt}
+        fi
+    fi
+
+    if [ x"${ca_crt}" = "x" ]; then
+      if [ "$type" = "self" ]; then
+          ca_crt=${zimbra_ca_crt}
+      elif [ "$type" = "comm" ]; then
+          ca_crt=${commercial_ca_crt}
+      fi
     fi
   fi  
 
@@ -963,11 +972,11 @@ verifycrt() {
   fi
 
   # check validity of the cert
-  result=`openssl verify -purpose sslserver -CAfile $crt $crt`
+  result=`openssl verify -purpose sslserver -CAfile $ca_crt $crt`
   if [ x"${result}" = x"${crt}: OK" ]; then
-    echo "Valid Certificate: $result"
+   echo "Valid Certificate: $result"
   else
-  	echo "${ERROR_PREFIX} Invalid Certificate: $result"
+    echo "${ERROR_PREFIX} Invalid Certificate: $result"
     exit 1
   fi
 }
@@ -976,13 +985,13 @@ verifycrtchain () {
     cafile=$1 
     crt=$2
    
-   	result=`openssl verify -purpose sslserver -CAfile $cafile $crt`
+     result=`openssl verify -purpose sslserver -CAfile $cafile $crt`
     
     if [ x"${result}" = x"${crt}: OK" ]; then
         echo "Valid Certificate Chain: $result"
     else
-    	echo "${ERROR_PREFIX} Invalid Certificate Chain: $result"
-    	exit 1
+      echo "${ERROR_PREFIX} Invalid Certificate Chain: $result"
+      exit 1
     fi
 }
 
