bug: 83893 Only check on store certs if store is installed
http://bugzilla.zimbra.com/show_bug.cgi?id=83893

diff --git a/ZimbraServer/src/bin/zmcertmgr b/ZimbraServer/src/bin/zmcertmgr
--- a/ZimbraServer/src/bin/zmcertmgr
+++ b/ZimbraServer/src/bin/zmcertmgr
@@ -1189,27 +1189,29 @@ checkCertExpiration() {
   if [ $VIEW = "all" -o $VIEW = "mailboxd" ]; then
     service_der=/opt/zimbra/mailboxd/etc/mailboxd.der
     service_crt=/opt/zimbra/mailboxd/etc/mailboxd.pem
+    if [ -f ${mailboxd_keystore} -a -d "/opt/zimbra/mailboxd" ]; then
     #echo "::service mailboxd::"
-    tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "${ERROR_PREFIX} Failed to create tmpfile" && exit 1)
-    ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
-      -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} > ${tmpfile} 2>&1
-    if [ $? != 0 ]; then
-      echo "${ERROR_PREFIX} failed to export ${service_crt} from keystore."
-      echo
-      cat $tmpfile
-      echo
-    fi
-    rm -f $tmpfile 2>/dev/null
-    if [ -f "${service_der}" ]; then
-      ${openssl} x509  -inform DER -outform PEM -in ${service_der} -out ${service_crt}
-      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "${ERROR_PREFIX} Failed to create tmpfile" && exit 1)
+      ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
+        -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} > ${tmpfile} 2>&1
       if [ $? != 0 ]; then
-        status=1
-        echo "${service_crt} is expiring within ${exp_thres_days} days."
-        ${openssl} x509  -in ${service_crt} -enddate -noout 
+        echo "${ERROR_PREFIX} failed to export ${service_crt} from keystore."
+        echo
+        cat $tmpfile
+        echo
       fi
-    else 
-      echo "${ERROR_PREFIX} ${service_crt} does not exist"
+      rm -f $tmpfile 2>/dev/null
+      if [ -f "${service_der}" ]; then
+        ${openssl} x509  -inform DER -outform PEM -in ${service_der} -out ${service_crt}
+        ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+        if [ $? != 0 ]; then
+          status=1
+          echo "${service_crt} is expiring within ${exp_thres_days} days."
+          ${openssl} x509  -in ${service_crt} -enddate -noout 
+        fi
+      else 
+        echo "${ERROR_PREFIX} ${service_crt} does not exist"
+      fi
     fi
   fi
 
@@ -1266,7 +1268,7 @@ viewdeployedcrt() {
   if [ $VIEW = "all" -o $VIEW = "mailboxd" ]; then
     service_der=/opt/zimbra/mailboxd/etc/mailboxd.der
     service_crt=/opt/zimbra/mailboxd/etc/mailboxd.pem
-    if [ -f ${mailboxd_keystore} ]; then
+    if [ -f ${mailboxd_keystore} -a -d "/opt/zimbra/mailboxd" ]; then
       echo "::service mailboxd::"
       tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "${ERROR_PREFIX} Failed to create tmpfile" && exit 1)
       ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
