bug: 21241 Modify the certificate upload wizard, so user will be able to upload root CA and multiple intermediate CAs.
http://bugzilla.zimbra.com/show_bug.cgi?id=21241

diff --git a/ZimbraServer/src/bin/zmcertmgr b/ZimbraServer/src/bin/zmcertmgr
--- a/ZimbraServer/src/bin/zmcertmgr
+++ b/ZimbraServer/src/bin/zmcertmgr
@@ -869,6 +869,20 @@ verifycrt () {
   fi
 }
 
+verifycrtchain () {
+    cafile=$1 
+    crt=$2
+   
+   	result=`openssl verify -purpose sslserver -CAfile $cafile $crt`
+    
+    if [ x"${result}" = x"${crt}: OK" ]; then
+        echo "Valid Certificate Chain: $result"
+    else
+    	echo "${ERROR_PREFIX} Invalid Certificate Chain: $result"
+    	exit 1
+    fi
+}
+
 migrate () {
   initSSLDirs
   prev_ssl_directory=${zimbra_home}/ssl/ssl
@@ -973,6 +987,8 @@ elif [ x"$ACTION" = "xinstall" ]; then
   install $@
 elif [ x"$ACTION" = "xverifycrt" ]; then
   verifycrt $@
+ elif [ x"$ACTION" = "xverifycrtchain" ]; then
+  verifycrtchain $@
 elif [ x"$ACTION" = "xmigrate" ]; then
   migrate $@
 else
