bug: 20601    - mktemp changes for deb based distros    - error handling for mktemp in failure cases
http://bugzilla.zimbra.com/show_bug.cgi?id=20601

diff --git a/ZimbraServer/src/bin/zmcertmgr b/ZimbraServer/src/bin/zmcertmgr
--- a/ZimbraServer/src/bin/zmcertmgr
+++ b/ZimbraServer/src/bin/zmcertmgr
@@ -172,7 +172,7 @@ createCAKey() {
   createCASerial
 
   echo -n "** Creating CA private key ${zimbra_ca_key}..."
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   openssl req -batch -subj "${SUBJECT}" \
     -config ${zimbra_ssl_conf} \
     -new -newkey rsa:1024 -nodes  \
@@ -196,7 +196,7 @@ createCACert() {
 
   echo -n "** Creating CA cert ${zimbra_ca_crt}..."
 
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   openssl x509 -trustout \
     -signkey ${zimbra_ca_key} \
     -days ${validation_days} \
@@ -226,7 +226,7 @@ createKeystore () {
   
   #4. Loading keys and certificates via PKCS12 
   #(you need both the private key and the certificate in the keystore.)
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   openssl pkcs12 \
     -inkey ${server_key} -in ${server_crt} -name ${mailboxd_server} \
     -export -out ${zimbra_ssl_directory}/${mailboxd_server}.pkcs12 \
@@ -249,7 +249,7 @@ createKeystore () {
 
 updateCACERTS() {
   echo -n "** Importing CA ${zimbra_ca_crt} into CACERTS..."
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   ${zimbra_home}/java/bin/keytool -delete -alias my_ca -keystore ${CACERTS} -storepass ${mailboxd_truststore_password} 2> /dev/null
   ${zimbra_home}/java/bin/keytool -import -noprompt -keystore ${CACERTS} -file ${zimbra_ca_crt} -alias my_ca -storepass ${mailboxd_truststore_password} > ${tmpfile} 2>&1
   if [ $? != 0 ]; then
@@ -274,7 +274,7 @@ createCA() {
     createConf
   fi
 
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   chown zimbra ${tmpfile}
   if [ ! -f ${zimbra_ca_key} ]; then
     echo -n "** Retrieving CA private key from ldap..."
@@ -287,7 +287,7 @@ createCA() {
   fi
   rm -f ${tmpfile} 2> /dev/null
 
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   chown zimbra ${tmpfile}
   if [ ! -f ${zimbra_ca_crt} ]; then
     echo -n "** Retrieving CA cert from ldap..."
@@ -396,7 +396,7 @@ createCASerial() {
 createServerCertReq() {
 
   echo -n "** Creating server cert request ${server_csr}..."
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
 
 
   openssl req -new -nodes -out ${server_csr} -keyout ${server_key} \
@@ -440,7 +440,7 @@ createServerCert() {
     gencsr
   fi
 
-  tmpfile=`mktemp -t zmcertmgr.XXXX` 
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   echo -n "** Signing cert request ${server_csr}..."
   if [ -s ${zimbra_ca_directory}/index.txt -o ! -e ${zimbra_ca_directory}/index.txt ]; then
     cp -f /dev/null ${zimbra_ca_directory}/index.txt
