Integrated the following from //depot/FRANKLIN/...: Change 117200 by brian@brianMP-franklin on 2008/09/30 22:26:20
bug: 17423, 20504
consistent reload/restart/status in startup scripts

http://bugzilla.zimbra.com/show_bug.cgi?id=17423
http://bugzilla.zimbra.com/show_bug.cgi?id=20504

diff --git a/ZimbraServer/src/bin/zmclamdctl b/ZimbraServer/src/bin/zmclamdctl
--- a/ZimbraServer/src/bin/zmclamdctl
+++ b/ZimbraServer/src/bin/zmclamdctl
@@ -89,6 +89,7 @@ case "$1" in
       --config-file=${zimbra_home}/conf/freshclam.conf -d --checks=12 \
         >> ${zimbra_log_directory}/freshclam.log 2>&1 &
 
+    echo -n "Starting clamd..."
     ${zimbra_home}/clamav/sbin/clamd \
       --config-file=${zimbra_home}/conf/clamd.conf \
         >> ${zimbra_log_directory}/clamd.log 2>&1 &
@@ -96,11 +97,12 @@ case "$1" in
     for ((i = 0; i < 12; i++)); do
       checkrunning
       if [ $running = 1 ]; then
+        echo "done."
         exit 0
       fi
       sleep 5
     done
-    echo "clamd failed to start"
+    echo "failed."
     exit 1
    ;;
   
@@ -124,6 +126,7 @@ case "$1" in
    ;;
 
   'stop')
+    echo -n "Stopping clamd..."
     if [ -f /opt/zimbra/log/freshclam.pid ]; then
       cpid=`cat /opt/zimbra/log/freshclam.pid`
       kill -TERM "$cpid" 2> /dev/null
@@ -140,12 +143,17 @@ case "$1" in
         break
       fi
       kill $cpid
-      echo -n "."
     done
+    if [ -s ${pidfile} ]; then
+      echo "failed."
+      exit 1
+    else
+      echo "done."
+    fi
     exit 0
   ;;
   
-  'restart')
+  'restart'|'reload')
     $0 stop
     $0 start
   ;;
diff --git a/ZimbraServer/src/bin/zmmailboxdctl b/ZimbraServer/src/bin/zmmailboxdctl
--- a/ZimbraServer/src/bin/zmmailboxdctl
+++ b/ZimbraServer/src/bin/zmmailboxdctl
@@ -98,55 +98,61 @@ case "$1" in
       if [ -z "`echo ${mailboxd_java_options} | grep Xss`" ]; then
         mailboxd_java_options="${mailboxd_java_options} -Xss${mailboxd_thread_stack_size}"
       fi
-
+      echo -n "Starting mailboxd..."
       sudo ${zimbra_home}/libexec/zmmailboxdmgr start \
         -Xms${jm}m -Xmx${jm}m ${mailboxd_java_options} < /dev/null > /dev/null 2>&1
       status=$?
       if [ $status = 0 ]; then
-        echo "mailboxd started."
+        echo "done."
       else
-        echo "mailboxed failed to start."
+        echo "failed."
       fi
       exit $status
     ;;
 
-    'kill')
+    'kill'|'stop')
+
+      echo -n "Stopping mailboxd..."
+      sudo ${zimbra_home}/libexec/zmmailboxdmgr status
+      if [ $? != 0 ]; then
+        echo "mailboxd is not running."
+        exit 0
+      fi
       lines=`wc -l ${zimbra_home}/log/zmmailboxd.out | awk '{print $1}'`
       sudo ${zimbra_home}/libexec/zmmailboxdmgr threaddump
       sleep 2
       newlines=`wc -l ${zimbra_home}/log/zmmailboxd.out | awk '{print $1}'`
       difflines=`expr $newlines - $lines`
       tail -${difflines} ${zimbra_home}/log/zmmailboxd.out > ${zimbra_home}/log/stacktrace.$$
-
       sudo ${zimbra_home}/libexec/zmmailboxdmgr stop 
+      if [ $? = 0 ]; then
+        echo "done."
+      else 
+        echo "failed."
+      fi 
       exit 0
     ;;
 
-    'stop')
-
-      lines=`wc -l ${zimbra_home}/log/zmmailboxd.out | awk '{print $1}'`
-      sudo ${zimbra_home}/libexec/zmmailboxdmgr threaddump
-      sleep 2
-      newlines=`wc -l ${zimbra_home}/log/zmmailboxd.out | awk '{print $1}'`
-      difflines=`expr $newlines - $lines`
-      tail -${difflines} ${zimbra_home}/log/zmmailboxd.out > ${zimbra_home}/log/stacktrace.$$
-  
-      sudo ${zimbra_home}/libexec/zmmailboxdmgr stop
-      exit 0
-    ;;
     
-    'restart')
+    'restart'|'reload')
         $0 stop
         $0 start
     ;;
     
     'status')
+      echo -n "mailboxd is "
       sudo ${zimbra_home}/libexec/zmmailboxdmgr status
-      exit $?
+      if [ $? = 0 ]; then
+        echo "running."
+        exit 0
+      else 
+        echo "not running."
+        exit 1
+      fi
     ;;
 
     *)
-      echo "Usage: $0 start|stop|kill|restart|status"
+      echo "Usage: $0 start|stop|kill|restart|reload|status"
       exit 1
     ;;
 esac
diff --git a/ZimbraServer/src/bin/zmmtactl b/ZimbraServer/src/bin/zmmtactl
--- a/ZimbraServer/src/bin/zmmtactl
+++ b/ZimbraServer/src/bin/zmmtactl
@@ -19,10 +19,20 @@
 BASE=/opt/zimbra
 SCRIPTS="zmmtaconfigctl postfix zmsaslauthdctl"
 
+rewriteconfig() {
+  echo -n "Rewriting configuration files..."
+  /opt/zimbra/libexec/zmmtaconfig antispam antivirus mta sasl  > /dev/null 2>&1
+  if [ $? = 0 ]; then
+    echo "done."
+  else
+    echo "failed."
+  fi
+}
+
 case "$1" in 
 	start)
 		if [ x$2 = "x" ]; then
-			/opt/zimbra/libexec/zmmtaconfig antispam antivirus mta sasl
+      rewriteconfig
 		fi
 		STATUS=0
 		for i in $SCRIPTS; do
@@ -40,18 +50,22 @@ case "$1" in
 			/opt/zimbra/bin/$i stop
 		done
 	;;
-	reload)
+	reload|restart)
 		if [ x$2 = "x" ]; then
-			/opt/zimbra/libexec/zmmtaconfig antispam antivirus mta sasl
+      rewriteconfig
 		fi
 		for i in $SCRIPTS; do
-			/opt/zimbra/bin/$i reload
+      if [ "x$i" = "xpostfix" ]; then
+        /opt/zimbra/bin/$i reload
+      else 
+			  /opt/zimbra/bin/$i $1
+      fi
 		done
 	;;
 	status)
 		STATUS=0
 		for i in $SCRIPTS; do
-			/opt/zimbra/bin/$i status
+			/opt/zimbra/bin/$i status > /dev/null 2>&1
 			R=$?
 			if [ $R -ne "0" ]; then
 				echo "$i is not running"
@@ -61,7 +75,7 @@ case "$1" in
 		exit $STATUS
 	;;
 	*)
-		echo "$0 start|stop|reload|status"
+		echo "$0 start|stop|restart|reload|status"
 		exit 1
 	;;
 esac
diff --git a/ZimbraServer/src/bin/zmswatchctl b/ZimbraServer/src/bin/zmswatchctl
--- a/ZimbraServer/src/bin/zmswatchctl
+++ b/ZimbraServer/src/bin/zmswatchctl
@@ -16,78 +16,130 @@
 # ***** END LICENSE BLOCK *****
 # 
 
-BASE=/opt/zimbra
-CONFIG=$BASE/conf/swatchrc
-PIDFILE=${BASE}/log/swatch.pid
-LOGFILE=${BASE}/log/zmswatch.out
-
-if [ -f $PIDFILE ]; then
-	PID=`cat $PIDFILE`
+if [ x`whoami` != xzimbra ]; then
+    echo Error: must be run as zimbra user
+  exit 1
 fi
 
-source /opt/zimbra/.bashrc
+source `dirname $0`/zmshutil || exit 1
+zmsetvars \
+    zimbra_home \
+    zimbra_log_directory
+
+configfile=${zimbra_home}/conf/swatchrc
+pidfile=${zimbra_log_directory}/swatch.pid
+logfile=${zimbra_log_directory}/zmswatch.out
+pid=""
+
+getpid()
+{
+  if [ -f ${pidfile} ]; then
+    pid=$(cat ${pidfile})
+  fi
+}
+
+checkrunning()
+{
+  getpid
+  if [ "x$pid" = "x" ]; then
+    running=0
+  else
+    kill -0 $pid 2> /dev/null
+    if [ $? != 0 ]; then
+      pid=""
+      running=0
+    else
+      running=1
+    fi
+  fi
+}
 
 case "$1" in 
-	start)
-		if [ ! -f $CONFIG ]; then
-			zmsnmpinit
-		fi
-		if [ -f $CONFIG ]; then
-      # make sure it's not already running
-      if [ x$PID != 'x' ]; then
-        kill -0 $PID 2> /dev/null
-        if [ $? = 0 ]; then
-          exit 1
-        fi
+  start)
+    if [ ! -f ${configfile} ]; then
+      zmsnmpinit
+    fi
+
+    checkrunning
+    echo -n "Starting swatch..."
+    if [ $running = 1 ]; then
+      echo "swatch is already running."
+      exit 0
+    fi
+
+    ${zimbra_home}/libexec/swatch --config-file=${configfile} \
+      --use-cpan-file-tail \
+      --script-dir=/tmp -t /var/log/zimbra.log > $logfile 2>&1 &
+    pid=$!
+    if [ "x$pid" != 'x' ]; then
+      if [ -f $logfile ]; then
+        touch $logfile
       fi
-			$BASE/libexec/swatch --config-file=$BASE/conf/swatchrc \
-			--use-cpan-file-tail \
-			--script-dir=/tmp -t /var/log/zimbra.log > $LOGFILE 2>&1 &
-			PID=$!
-			echo $PID > $PIDFILE
-			chmod 644 $LOGFILE
-			if [ x$PID != 'x' ]; then
-				kill -0 $PID
-				exit $?
-			else
-				exit 1
-			fi
-		else
-			exit 1
-		fi
-	;;
-	stop)
-		if [ x$PID != 'x' ]; then
-			kill -TERM $PID
-		fi
-		rm -f $PIDFILE
-		if [ "x$platform" = "xMACOSX" ]; then
-				killall -TERM swatch > /dev/null 2>&1
-		else
-				killall -TERM ${zimbra_home}/libexec/swatch > /dev/null 2>&1
-		fi
-		exit 0
-	;;
-	reload)
-		if [ x$PID != 'x' ]; then
-			kill -HUP $PID
-		fi
-	;;
-	status)
-		if [ x$PID != 'x' ]; then
-			kill -0 $PID
-			R=$?
-			if [ $R -ne 0 ]; then
-				echo "swatch is not running"
-			fi
-			exit $R
-		else
-			echo "swatch is not running"
-			exit 1
-		fi
-	;;
-	*)
-		echo "$0 start|stop|reload|status"
-		exit 1
-	;;
+      chmod 644 $logfile
+      echo $pid > $pidfile
+    else
+      echo "failed."
+      exit 1
+    fi
+    checkrunning
+    if [ $running = 1 ]; then
+      echo "done."
+      exit 0
+    else
+      echo "failed."
+      exit 1
+    fi
+  ;;
+  stop)
+    checkrunning
+    echo -n "Stopping swatch..."
+    if [ $running = 0 ]; then
+      echo "swatch is not running."
+      exit 0
+    else
+      for ((i = 0; i < 30; i++)); do
+        kill -0 $pid 2> /dev/null
+        if [ $? != 0 ]; then
+          rm -rf ${pidfile}
+          break
+        fi
+        kill $pid
+        sleep 1
+      done
+    fi
+    if [ -s ${pidfile} ]; then
+      echo "failed."
+      exit 1
+    else
+      echo "done."
+    fi
+    exit 0
+  ;;
+  restart)
+    $0 stop
+    $0 start
+  ;;
+  reload)
+    checkrunning
+    if [ $running = 1 -a "x$pid" != "x" ]; then
+      echo -n "Reloading swatch..."
+      kill -HUP $pid
+      echo "done."
+    fi
+  ;;
+  status)
+    echo -n "zmswatch is "
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "not running."
+      exit 1
+    else
+      echo "running."
+      exit 0
+    fi
+  ;;
+  *)
+    echo "$0 start|stop|restart|reload|status"
+    exit 1
+  ;;
 esac
