bug: 49955 convert zmconfigdctl to watchdog script
http://bugzilla.zimbra.com/show_bug.cgi?id=49955

diff --git a/ZimbraServer/src/bin/zmconfigdctl b/ZimbraServer/src/bin/zmconfigdctl
--- a/ZimbraServer/src/bin/zmconfigdctl
+++ b/ZimbraServer/src/bin/zmconfigdctl
@@ -6,7 +6,7 @@
 # 
 # The contents of this file are subject to the Zimbra Public License
 # Version 1.3 ("License"); you may not use this file except in
-# compliance with the License.  You may obtain a copy of the License at
+# compliance with the License.	You may obtain a copy of the License at
 # http://www.zimbra.com/license.
 # 
 # Software distributed under the License is distributed on an "AS IS"
@@ -15,27 +15,37 @@
 # 
 
 if [ x`whoami` != xzimbra ]; then
-    echo Error: must be run as zimbra user
+	echo Error: must be run as zimbra user
   exit 1
 fi
 
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
-    zimbra_home \
-    zimbra_log_directory \
+	zimbra_home \
+	zimbra_log_directory \
 	zmmtaconfig_listen_port
 
 pid=""
 pidfile="${zimbra_log_directory}/zmconfigd.pid"
+
+ctlpid=""
+ctlpidfile="${zimbra_log_directory}/zmconfigdctl.pid"
 
 NC=`which nc 2>/dev/null`; NC=${NC:-`which netcat 2>/dev/null`}
 
 getpid()
 {
   if [ "x$ppid" != "x" ]; then
-  	pid=$ppid
+	pid=$ppid
   elif [ -f ${pidfile} ]; then
-    pid=$(cat ${pidfile})
+	pid=$(cat ${pidfile})
+  fi
+}
+
+getctlpid()
+{
+  if [ -f ${ctlpidfile} ]; then
+	ctlpid=$(cat ${ctlpidfile})
   fi
 }
 
@@ -43,104 +53,173 @@ checkrunning()
 {
   getpid
   if [ "x$pid" = "x" ]; then
-    running=0
+	running=0
   else
-    kill -0 $pid 2> /dev/null
-    if [ $? != 0 ]; then
-      pid=""
-      running=-1
-    else
+	kill -0 $pid 2> /dev/null
+	if [ $? != 0 ]; then
+	  pid=""
+	  running=-1
+	else
 		status=`echo STATUS | $NC -i 1 localhost ${zmmtaconfig_listen_port} 2>/dev/null`
 		if [ $? = 0 -a "x$status" = "xSUCCESS ACTIVE" ]; then
 			running=1
 		else
 			running=0
 		fi
-    fi 
+	fi 
   fi
 } 
+
+checkctlrunning()
+{
+  getctlpid
+  if [ "x$ctlpid" = "x" ]; then
+	ctlrunning=0
+  else
+	kill -0 $ctlpid 2> /dev/null
+	if [ $? != 0 ]; then
+	  ctlpid=""
+	  ctlrunning=0
+	else
+		ctlrunning=1
+	fi 
+  fi
+} 
+
+startzmconfigd()
+{
+	err=0
+	checkrunning
+	echo -n "Starting zmconfigd..."
+	if [ $running = 1 ]; then
+	  echo "zmconfigd is already running."
+	  return
+	fi
+	if [ "x$JYTHONPATH" = "x" ]; then
+	  echo "JYTHONPATH is unset!"
+	  err=1
+	  return
+	fi
+	# Grab the pid here, so we don't have to wait for the jvm to write the pid file
+	${zimbra_home}/libexec/zmconfigd >> ${zimbra_log_directory}/zmconfigd.log 2>&1 &
+	ppid=$!
+	for ((i = 0; i < 30; i++)) do
+	  checkrunning
+	  if [ $running = 1 ]; then
+		echo "done."
+		return
+	  fi
+	  if [ $running = -1 ]; then
+		echo "Failed to start"
+		err=1
+		return
+	  fi
+	  sleep 1
+	done
+	echo "failed."
+	err=1
+	return
+}
+
+daemon()
+{
+	echo "Starting zmconfigdctl...success"
+	while :; do
+		sleep 60
+		startzmconfigd >> /opt/zimbra/log/zmconfigd.log 2>&1
+	done
+	exit 0
+}
+
+startdaemon()
+{
+	startzmconfigd
+	daemon &
+	echo $! > ${ctlpidfile}
+}
+
+stopdaemon()
+{
+	checkctlrunning
+	if [ x$ctlpid != "x" ]; then
+		echo -n "Stopping zmconfigdctl..."
+		kill -15 $ctlpid 2> /dev/null
+		kill -0 $ctlpid 2> /dev/null
+		if [ $? != 0 ]; then
+		  ctlpid=""
+		  ctlrunning=0
+		  echo "success"
+		else
+			ctlrunning=1
+			echo "failed"
+		fi
+	else
+		echo "zmconfigdctl is not running"
+	fi
+}
 
 #
 # Main
 #
 case "$1" in
   'start')
-    checkrunning
-    echo -n "Starting zmconfigd..."
-    if [ $running = 1 ]; then
-      echo "zmconfigd is already running."
-      exit 0
-    fi
-	if [ "x$JYTHONPATH" = "x" ]; then
-      echo "JYTHONPATH is unset!"
-      exit 1
+	checkctlrunning
+	if [ $ctlrunning = 0 ]; then
+		startdaemon
+	else
+		startzmconfigd
+		exit ${err}
 	fi
-	# Grab the pid here, so we don't have to wait for the jvm to write the pid file
-    ${zimbra_home}/libexec/zmconfigd >> ${zimbra_log_directory}/zmconfigd.log 2>&1 &
-	ppid=$!
-    for ((i = 0; i < 30; i++)) do
-      checkrunning
-      if [ $running = 1 ]; then
-        echo "done."
-        exit 0
-      fi
-      if [ $running = -1 ]; then
-        echo "Failed to start"
-        exit 1
-      fi
-      sleep 1
-    done
-    echo "failed."
-    exit 1
    ;;
 
   'kill'|'stop')
-    checkrunning
-    echo -n "Stopping zmconfigd..."
-    if [ $running -lt 1 ]; then
-      echo "zmconfigd is not running."
-      exit 0
-    else 
-      for ((i = 0; i < 30; i++)); do
-        kill -0 $pid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -rf ${pidfile}
-          break
-        fi
-        kill $pid
-        sleep 1
-      done
-    fi
-    if [ -s ${pidfile} ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
-    fi
-    exit 0
+  	stopdaemon
+	checkrunning
+	echo -n "Stopping zmconfigd..."
+	if [ $running -lt 1 ]; then
+	  echo "zmconfigd is not running."
+	  exit 0
+	else 
+	  for ((i = 0; i < 30; i++)); do
+		kill -0 $pid 2> /dev/null
+		if [ $? != 0 ]; then
+		  rm -rf ${pidfile}
+		  break
+		fi
+		kill $pid
+		sleep 1
+	  done
+	fi
+	if [ -s ${pidfile} ]; then
+	  echo "failed."
+	  exit 1
+	else
+	  echo "done."
+	fi
+	exit 0
   ;;
 
-    
+	
   'restart'|'reload')
-    $0 stop
-    $0 start
+	$0 stop
+	$0 start
   ;;
   
   'status')
-    echo -n "zmconfigd is "
-    checkrunning
-    if [ $running -lt 1 ]; then
-      echo "not running." 
-      exit 1
-    else
-      echo "running."
-      exit 0
-    fi
+	echo -n "zmconfigd is "
+	checkrunning
+	if [ $running -lt 1 ]; then
+	  echo "not running." 
+	  exit 1
+	else
+	  echo "running."
+	  exit 0
+	fi
    ;;
-    
+	
   *)
-    echo "Usage: $0 start|stop|kill|restart|reload|status"
-    exit 1
+	echo "Usage: $0 start|stop|kill|restart|reload|status"
+	exit 1
   ;;
 
 esac
