bug: 45480 Rewrite of zmmtaconfig in python to run in the jython interpreter to improve speed. All zmprov operations are performed internally with the existing java code, as are zmlocalconfig lookups. Provutil convenience methods (gamcs, garpu, garpb, gamau) have been rewritten in python.
When launched as a daemon, will listen on localhost:zmmtaconfig_listen_port for rewrite requests from other processes.
If launched with rewrite requests on the command line, we will attempt to send them to a running daemon; 
if not available, we perform the rewrites and exit

utility libexec/configrewrite will send rewrite requests to the daemon, and launch zmmtaconfig standalone if it fails.
written in bash to avoid JVM instantiation delay if the daemon is already running.
when possible, all rewrites should be sent to the running daemon, since jvm instantiation of 
zmmtaconfig takes about 15 seconds

zmcontrol modified to add zmmtaconfig to service list (no zimbraServiceEnabled entry).  zmmtaconfig will run as a
standalone service, starting right after ldap.  At startup, zmmtaconfig automatically rewrites all config 
files on first run. zmmtaconfig will run on all servers, since so many services depend on it, and the
overhead is minimal

bin/*ctl scripts rewritten to take advantage of configrewrite for rewriting configuration files.  
norewrite directive should now propagate to all services at startup.

zmmtaconfig now handles rewrite duties of zmtlsctl, so we no longer modify any .in files
zmtlsctl modified - when invoked without arguments, just call configrewrite sasl webxml mailbox.  
If invoked with a mode, set the mode in ldap, then call configrewrite

sasl modified to use a config file listing services, maintained by zmmtaconfig, to avoid zmprov call
during startup.  If not present, falls back to calling zmprov to determine services.

various build fixes to support the new system

Startup time on test systems running all services decreased from ~4m15s to ~45s.  mailstore restarts (zmstorectl restart)
when zmmtaconfig daemon is running reduced from ~1m to ~13s.

http://bugzilla.zimbra.com/show_bug.cgi?id=45480

diff --git a/ZimbraServer/src/bin/zmconfigdctl b/ZimbraServer/src/bin/zmconfigdctl
--- a/ZimbraServer/src/bin/zmconfigdctl
+++ b/ZimbraServer/src/bin/zmconfigdctl
@@ -22,14 +22,19 @@ fi
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
     zimbra_home \
-    zimbra_log_directory
+    zimbra_log_directory \
+	zmmtaconfig_listen_port
 
 pid=""
-pidfile="${zimbra_log_directory}/zmmtaconfig.pid"
+pidfile="${zimbra_log_directory}/zmconfigd.pid"
+
+NC=`which nc 2>/dev/null`; NC=${NC:-`which netcat 2>/dev/null`}
 
 getpid()
 {
-  if [ -f ${pidfile} ]; then
+  if [ "x$ppid" != "x" ]; then
+  	pid=$ppid
+  elif [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
 }
@@ -43,9 +48,14 @@ checkrunning()
     kill -0 $pid 2> /dev/null
     if [ $? != 0 ]; then
       pid=""
-      running=0
+      running=-1
     else
-      running=1
+		status=`echo STATUS | $NC localhost ${zmmtaconfig_listen_port} 2>/dev/null`
+		if [ $? = 0 -a "x$status" = "xSUCCESS ACTIVE" ]; then
+			running=1
+		else
+			running=0
+		fi
     fi 
   fi
 } 
@@ -56,17 +66,27 @@ checkrunning()
 case "$1" in
   'start')
     checkrunning
-    echo -n "Starting zmmtaconfig..."
+    echo -n "Starting zmconfigd..."
     if [ $running = 1 ]; then
-      echo "zmmtaconfig is already running."
+      echo "zmconfigd is already running."
       exit 0
     fi
-    ${zimbra_home}/libexec/zmmtaconfig >> ${zimbra_log_directory}/zmmtaconfig.log 2>&1 
+	if [ "x$JYTHONPATH" = "x" ]; then
+      echo "JYTHONPATH is unset!"
+      exit 1
+	fi
+	# Grab the pid here, so we don't have to wait for the jvm to write the pid file
+    ${zimbra_home}/libexec/zmconfigd >> ${zimbra_log_directory}/zmconfigd.log 2>&1 &
+	ppid=$!
     for ((i = 0; i < 30; i++)) do
       checkrunning
       if [ $running = 1 ]; then
         echo "done."
         exit 0
+      fi
+      if [ $running = -1 ]; then
+        echo "Failed to start"
+        exit 1
       fi
       sleep 1
     done
@@ -76,9 +96,9 @@ case "$1" in
 
   'kill'|'stop')
     checkrunning
-    echo -n "Stopping zmmtaconfig..."
-    if [ $running = 0 ]; then
-      echo "zmmtaconfig is not running."
+    echo -n "Stopping zmconfigd..."
+    if [ $running -lt 1 ]; then
+      echo "zmconfigd is not running."
       exit 0
     else 
       for ((i = 0; i < 30; i++)); do
@@ -107,9 +127,9 @@ case "$1" in
   ;;
   
   'status')
-    echo -n "zmmtaconfig is "
+    echo -n "zmconfigd is "
     checkrunning
-    if [ $running = 0 ]; then
+    if [ $running -lt 1 ]; then
       echo "not running." 
       exit 1
     else
