bug: 83670 On debian/ubuntu based systems, use resolvconf to handle /etc/resolv.conf.  This allows on the fly updating of the resolver, based on whether or not dnscache is running.
http://bugzilla.zimbra.com/show_bug.cgi?id=83670

diff --git a/ZimbraServer/src/bin/zmdnscachectl b/ZimbraServer/src/bin/zmdnscachectl
--- a/ZimbraServer/src/bin/zmdnscachectl
+++ b/ZimbraServer/src/bin/zmdnscachectl
@@ -32,6 +32,11 @@ PID=""
 unbound=${zimbra_home}/libexec/zmunbound
 config=${zimbra_home}/conf/unbound.conf
 
+RESOLVCONF=false
+if [ -x /sbin/resolvconf ]; then
+  RESOLVCONF=true
+fi
+
 rewriteconfig() {
     /opt/zimbra/libexec/configrewrite dnscache > /dev/null 2>&1
 }
@@ -60,28 +65,44 @@ checkrunning()
 
 start()
 {
-        checkrunning
-        if [ $RUNNING = 0 ]; then
-          if [ x$1 = "x" ]; then
-            rewriteconfig
+  checkrunning
+  if [ $RUNNING = 0 ]; then
+    if [ x$1 = "x" ]; then
+      rewriteconfig
+    fi
+    if [ x"$RESOLVCONF" = "xtrue" ]; then
+      /opt/zimbra/unbound/sbin/unbound-checkconf -o interface | (
+        default=yes
+        while read interface; do
+          default=no
+          if [ "x$interface" = x127.0.0.1 ]; then
+            echo "nameserver 127.0.0.1"
+          elif [ "x$interface" = x::1 ]; then
+            echo "nameserver ::1"
           fi
-          sudo $unbound
-          if [ $? != 0 ]; then
-            echo "Failed to start dnscache: $?"
-            exit 1
-          fi
-          sleep 2
-          getpid
-          echo "Started dnscache: pid $PID"
-        else
-          echo "dnscache already running: pid $PID"
-          exit 0
-        fi
+        done
+      ) | sudo /sbin/resolvconf -a lo.zimbra-unbound
+    fi
+    sudo $unbound
+    if [ $? != 0 ]; then
+      echo "Failed to start dnscache: $?"
+      exit 1
+    fi
+    sleep 2
+    getpid
+    echo "Started dnscache: pid $PID"
+  else
+    echo "dnscache already running: pid $PID"
+    exit 0
+  fi
 }
 
 stop()
 {
         checkrunning
+        if [ x"$RESOLVCONF" = "xtrue" ]; then
+            sudo /sbin/resolvconf -d lo.zimbra-unbound
+        fi
         if [ $RUNNING = 0 ]; then
           echo "dnscache not running"
           exit 0
