bug:415423
zmlogprocess: check zimbraServiceEnabled for logger, fail start if not enabled.

http://bugzilla.zimbra.com/show_bug.cgi?id=415423

diff --git a/ZimbraServer/src/bin/zmlogswatchctl b/ZimbraServer/src/bin/zmlogswatchctl
--- a/ZimbraServer/src/bin/zmlogswatchctl
+++ b/ZimbraServer/src/bin/zmlogswatchctl
@@ -64,6 +64,12 @@ case "$1" in
       exit 0
     fi
 
+    zmprov gs `zmhostname` zimbraServiceEnabled | grep -qw logger
+    if [ $? = 1 ]; then
+        echo "zimbra logger service is not enabled!  failed."
+        exit 1
+    fi
+
     if [ ! -d ${zimbra_tmp_directory} ]; then
       mkdir -p ${zimbra_tmp_directory} > /dev/null 2>&1
     fi
