bug: 76822 Ensure memcached is actually installed when trying to start
http://bugzilla.zimbra.com/show_bug.cgi?id=76822

diff --git a/ZimbraServer/src/bin/zmmemcachedctl b/ZimbraServer/src/bin/zmmemcachedctl
--- a/ZimbraServer/src/bin/zmmemcachedctl
+++ b/ZimbraServer/src/bin/zmmemcachedctl
@@ -55,6 +55,11 @@ checkrunning()
 case "$1" in 
   start)
 
+    if [ ! -L /opt/zimbra/memcached ]; then
+      echo "Error: memcached not installed"
+      exit 1
+    fi
+
     checkrunning
     echo -n "Starting ${servicename}..."
     if [ $running = 1 ]; then
