Integrated the following from //depot/FRANKLIN/...: Change 115600 by brian@brian-franklin on 2008/09/19 10:13:04
bug: 9050
clean up init scripts

http://bugzilla.zimbra.com/show_bug.cgi?id=9050

diff --git a/ZimbraServer/src/bin/zmmtaconfigctl b/ZimbraServer/src/bin/zmmtaconfigctl
--- a/ZimbraServer/src/bin/zmmtaconfigctl
+++ b/ZimbraServer/src/bin/zmmtaconfigctl
@@ -18,7 +18,7 @@
 
 if [ x`whoami` != xzimbra ]; then
     echo Error: must be run as zimbra user
-	exit 1
+  exit 1
 fi
 
 source `dirname $0`/zmshutil || exit 1
@@ -26,49 +26,102 @@ zmsetvars \
     zimbra_home \
     zimbra_log_directory
 
+pid=""
+pidfile="${zimbra_log_directory}/zmmtaconfig.pid"
+
+getpid()
+{
+  if [ -f ${pidfile} ]; then
+    pid=$(cat ${pidfile})
+  fi
+}
+
+checkrunning()
+{
+  getpid
+  if [ "x$pid" = "x" ]; then
+    running=0
+  else
+    kill -0 $pid 2> /dev/null
+    if [ $? != 0 ]; then
+      pid=""
+      running=0
+    else
+      running=1
+    fi 
+  fi
+} 
+
 #
 # Main
 #
 case "$1" in
-    'start')
-		${zimbra_home}/libexec/zmmtaconfig </dev/null  \
-		    >> ${zimbra_log_directory}/zmmtaconfig.log 2>&1 
-        ;;
+  'start')
+    checkrunning
+    echo -n "Starting zmmtaconfig..."
+    if [ $running = 1 ]; then
+      echo "zmmtaconfig is already running."
+      exit 0
+    fi
+    ${zimbra_home}/libexec/zmmtaconfig >> ${zimbra_log_directory}/zmmtaconfig.log 2>&1 
+    for ((i = 0; i < 30; i++)) do
+      checkrunning
+      if [ $running = 1 ]; then
+        echo "done."
+        exit 0
+      fi
+      sleep 1
+    done
+    echo "failed."
+    exit 1
+   ;;
 
-    'kill')
-		if [ -f "/opt/zimbra/log/zmmtaconfig.pid" ]; then
-			cpid=`cat /opt/zimbra/log/zmmtaconfig.pid`
-			kill -TERM "$cpid" 2> /dev/null
-			rm -f /opt/zimbra/log/zmmtaconfig.pid
-		fi
-		exit 0
-        ;;
+  'kill'|'stop')
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "zmmtaconfig is not running."
+      exit 0
+    else 
+      echo -n "Stopping zmmtaconfig..."
+      for ((i = 0; i < 30; i++)); do
+        kill -0 $pid 2> /dev/null
+        if [ $? != 0 ]; then
+          rm -rf ${pidfile}
+          break
+        fi
+        kill $pid
+        sleep 1
+      done
+    fi
+    if [ -s ${pidfile} ]; then
+      exit 1
+    else
+      echo "done."
+    fi
+    exit 0
+  ;;
 
-    'stop')
-		if [ -f "/opt/zimbra/log/zmmtaconfig.pid" ]; then
-			cpid=`cat /opt/zimbra/log/zmmtaconfig.pid`
-			kill -TERM "$cpid" 2> /dev/null
-			rm -f /opt/zimbra/log/zmmtaconfig.pid
-		fi
-		exit 0
-        ;;
     
-    'restart'|'reload')
-        $0 stop
-        $0 start
-        ;;
-	
-    'status')
-		if [ -f "/opt/zimbra/log/zmmtaconfig.pid" ]; then
-			cpid=`cat /opt/zimbra/log/zmmtaconfig.pid`
-			kill -0 "$cpid" 2> /dev/null
-			exit $?
-		fi
-		exit 1
-    ;;
+  'restart'|'reload')
+    $0 stop
+    $0 start
+  ;;
+  
+  'status')
+    echo -n "zmmtaconfig is "
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "not running." 
+      exit 1
+    else
+      echo "running."
+      exit 0
+    fi
+   ;;
     
-    *)
-        echo "Usage: $0 start|stop|kill|restart|status"
-        exit 1
-        ;;
+  *)
+    echo "Usage: $0 start|stop|kill|restart|status"
+    exit 1
+  ;;
+
 esac
diff --git a/ZimbraServer/src/bin/zmsaslauthdctl b/ZimbraServer/src/bin/zmsaslauthdctl
--- a/ZimbraServer/src/bin/zmsaslauthdctl
+++ b/ZimbraServer/src/bin/zmsaslauthdctl
@@ -21,71 +21,112 @@ if [ x`whoami` != xzimbra ]; then
   exit 1
 fi
 
-platform=`/opt/zimbra/libexec/get_plat_tag.sh`
 
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
     zimbra_home \
     zimbra_log_directory
 
+platform=$(${zimbra_home}/libexec/get_plat_tag.sh)
+pid=""
+saslversion="2.1.22.3z"
+pidfile="${zimbra_log_directory}/zmmtaconfig.pid"
+pidfile="${zimbra_home}/cyrus-sasl/state/saslauthd.pid"
+
 rewriteconfig() {
-  /opt/zimbra/libexec/zmmtaconfig sasl > /dev/null 2>&1
+  ${zimbra_home}/libexec/zmmtaconfig sasl > /dev/null 2>&1
+}
+
+getpid()
+{
+  if [ -f ${pidfile} ]; then
+    pid=$(cat ${pidfile})
+  fi
+}
+
+checkrunning()
+{
+  getpid
+  if [ "x$pid" = "x" ]; then
+    running=0
+  else
+    kill -0 $pid 2> /dev/null
+    if [ $? != 0 ]; then
+      pid=""
+      running=0
+    else
+      running=1
+    fi
+  fi
 }
 
 #
 # Main
 #
 case "$1" in
-    'start')
-    if [ -f ${zimbra_home}/cyrus-sasl-2.1.22.3z/state/saslauthd.pid ]; then
-      cpid=`cat ${zimbra_home}/cyrus-sasl-2.1.22.3z/state/saslauthd.pid`
-      kill -0 "$cpid" 2> /dev/null
-      if [ $? -eq 0 ]; then
-        exit 0
-      fi
+  'start')
+    checkrunning
+    echo -n "Starting saslauthd..."
+    if [ $running = 1 ]; then
+      echo "already running."
+      exit 0
     fi
-    mkdir -p ${zimbra_home}/cyrus-sasl-2.1.22.3z/state
+    mkdir -p ${zimbra_home}/cyrus-sasl/state
     if [ x$2 = "x" ]; then
       rewriteconfig
     fi
-    ${zimbra_home}/cyrus-sasl-2.1.22.3z/sbin/saslauthd -r -a zimbra 
-        ;;
-
-    'kill')
-    cpid=`cat ${zimbra_home}/cyrus-sasl-2.1.22.3z/state/saslauthd.pid`
-        kill -TERM "$cpid" 2> /dev/null
-        ;;
-
-    'stop')
-    if [ -f ${zimbra_home}/cyrus-sasl-2.1.22.3z/state/saslauthd.pid ]; then
-      cpid=`cat ${zimbra_home}/cyrus-sasl-2.1.22.3z/state/saslauthd.pid`
-      kill -TERM "$cpid" 2> /dev/null
-    fi
-    if [ -f ${zimbra_home}/cyrus-sasl-2.1.22.3z/state/saslauthd.pid ]; then
-      if [ x$platform = "xMACOSX" -o "x$platform" = "xMACOSXx86" ]; then
-        killall -TERM saslauthd > /dev/null 2>&1
-      else
-        killall -TERM ${zimbra_home}/cyrus-sasl-2.1.22.3z/sbin/saslauthd > /dev/null 2>&1
+    ${zimbra_home}/cyrus-sasl/sbin/saslauthd -r -a zimbra 
+    for ((i = 0; i < 30; i++)) do
+      checkrunning
+      if [ $running = 1 ]; then
+        echo "done."
+        exit 0
       fi
+      sleep 1
+    done
+    echo "failed."
+    exit 1
+    ;;
+
+  'kill'|'stop')
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "saslauthd is not running."
+      exit 0
+    else
+      echo -n "Stopping saslauthd..."
+      for ((i = 0; i < 30; i++)); do
+        kill -0 $pid 2> /dev/null
+        if [ $? != 0 ]; then
+          rm -rf ${pidfile}
+          break
+        fi
+        kill $pid
+        sleep 1
+      done
+    fi
+    if [ -s ${pidfile} ]; then
+      exit 1
+    else
+      echo "done."
     fi
     exit 0
-        ;;
-    
-    'restart'|'reload')
-        $0 stop
-        $0 start
-        ;;
+    ;;
+
+  'restart'|'reload')
+    $0 stop
+    $0 start
+    ;;
   
   'status')
-    cpid=`cat ${zimbra_home}/cyrus-sasl-2.1.22.3z/state/saslauthd.pid 2> /dev/null`
-    kill -0 "$cpid" 2> /dev/null
-    rc=$?
-    if [ $rc = 0 ]; then
-      echo "saslauthd is running with pid $cpid"
+    checkrunning
+    if [ $running = 1 ]; then
+      echo "saslauthd is running with pid $pid"
+      exit 0
     else 
-      echo "saslauthd is not running"
+      echo "saslauthd is not running."
+      exit 1
     fi
-    exit $rc
     ;;
     
     *)
