bug 66072
report the invalid host name error explicitly. Due to zmconfigd is very complicated, I put the configuration generation result to the last line of nginx.conf (as a comment). zmnginxctl will read this line and if there is an error, zmnginxctl will prompt that to screen and don't start nginx at all.

fix in main

http://bugzilla.zimbra.com/show_bug.cgi?id=66072

diff --git a/ZimbraServer/src/bin/zmnginxctl b/ZimbraServer/src/bin/zmnginxctl
--- a/ZimbraServer/src/bin/zmnginxctl
+++ b/ZimbraServer/src/bin/zmnginxctl
@@ -78,6 +78,16 @@ case "$1" in
       exit 1
     fi
 
+    # read the last line of nginx.conf which indicates the conf gen result
+    res=`tail -n 1 ${configfile}`
+    if ! [[ $res =~ __SUCCESS__ ]]; then
+        echo "failed."
+        msg=`echo $res | awk -F ':' '{print $2}'`
+        if [ x"$msg" = "x" ]; then msg="unknown"; fi
+        echo "nginx start failed. reason: $msg"
+        exit 1
+    fi
+
     sudo ${zimbra_home}/${servicename}/sbin/${servicename} -c ${configfile}
     for ((i=0; i < 30; i++)); do
       checkrunning
