bug: none Don't keep trying to start nginx if generating the config file failed.

diff --git a/ZimbraServer/src/bin/zmnginxctl b/ZimbraServer/src/bin/zmnginxctl
--- a/ZimbraServer/src/bin/zmnginxctl
+++ b/ZimbraServer/src/bin/zmnginxctl
@@ -68,6 +68,12 @@ case "$1" in
       ${zimbra_home}/libexec/zmmtaconfig imapproxy > /dev/null 2>&1
     fi
 
+    if [ ! -f ${configfile} ]; then
+      echo "failed."
+      echo "${configfile} generation failed."
+      exit 1
+    fi
+
     sudo ${zimbra_home}/${servicename}/sbin/${servicename} -c ${configfile}
     for ((i=0; i < 30; i++)); do
       checkrunning
