bug: none If zmopendkimctl fails to start, log it and exit

diff --git a/ZimbraServer/src/bin/zmopendkimctl b/ZimbraServer/src/bin/zmopendkimctl
--- a/ZimbraServer/src/bin/zmopendkimctl
+++ b/ZimbraServer/src/bin/zmopendkimctl
@@ -69,6 +69,10 @@ start()
             rewriteconfig
           fi
           $odk -x $config -u zimbra
+          if [ $? != 0 ]; then
+            echo "Failed to start opendkim: $?"
+            exit 1
+          fi
           sleep 2
           getpid
           echo "Started opendkim: pid $PID"
