Bug: 46229 - Added "-h" and "--help" options.
http://bugzilla.zimbra.com/show_bug.cgi?id=46229

diff --git a/ZimbraServer/src/bin/zmskindeploy b/ZimbraServer/src/bin/zmskindeploy
--- a/ZimbraServer/src/bin/zmskindeploy
+++ b/ZimbraServer/src/bin/zmskindeploy
@@ -25,6 +25,9 @@ zmsetvars \
 
 usage() {
     echo "Usage: "`basename $0`" <path/to/skin/dir/or/zipfile>" >&2
+    echo ""
+    echo "    -h, --help      Print usage information" >&2
+    echo ""
 #    echo "  -v              verbose" >&2
 #    echo "  -n              make this deploy non-authoritative" >&2
 #    echo "  -d              mark the package as defined" >&2
@@ -34,11 +37,34 @@ usage() {
     exit 2
 }
 
-# Check the number of arguments
-if [ "$#" -ne "1" ]; then
-    echo "Invalid argument(s)" >&2
-    usage
-fi
+
+SKIN_SRC=""
+while [ $# -gt 0 ]
+do
+    case $1 in
+        -h | --help)
+            usage
+            exit
+            ;;
+        -*)
+            echo "ERROR: Unknown option $1"
+            usage
+            exit -1
+            ;;
+        *)
+            if [ "${SKIN_SRC}x" != "x" ]
+            then
+                echo "ERROR: Invalid number arguments" >&2
+                usage
+                exit -1
+            else
+                SKIN_SRC=$1
+            fi
+            shift
+            ;;
+    esac
+done
+
 
 SIMPLE_DATE=`date +%y%m%d%H%M%S`
 
