Integrated the following from //depot/FRANKLIN/...: Change 117099 by brian@brianMP-franklin on 2008/09/30 11:39:25
bug: none

diff --git a/ZimbraServer/src/bin/zmsshkeygen b/ZimbraServer/src/bin/zmsshkeygen
--- a/ZimbraServer/src/bin/zmsshkeygen
+++ b/ZimbraServer/src/bin/zmsshkeygen
@@ -29,6 +29,11 @@ keyfile="${zimbra_home}/.ssh/zimbra_identity"
 
 mkdir -p ${zimbra_home}/.ssh
 
+if [ ! -d "${zimbra_home}/.ssh" ]; then
+  echo "Unable to create ${zimbra_home}/.ssh."
+  exit 1
+fi
+
 chmod 700 ${zimbra_home}/.ssh
 
 rm -f ${keyfile}
