bug: 18687 Exit if /opt/zimbra/amavisd doesn't exist
http://bugzilla.zimbra.com/show_bug.cgi?id=18687

diff --git a/ZimbraServer/src/bin/zmtrainsa b/ZimbraServer/src/bin/zmtrainsa
--- a/ZimbraServer/src/bin/zmtrainsa
+++ b/ZimbraServer/src/bin/zmtrainsa
@@ -117,6 +117,11 @@ if [ x`whoami` != xzimbra ]; then
 	exit 1
 fi
 
+if [ ! -h "/opt/zimbra/amavisd" ]; then
+    echo "Error: SpamAssassin not installed"
+    exit 1
+fi
+
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
 	zimbra_home \
